name: main pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run unit tests
        run: |
          cd backend/tests/
          pytest *unitTests.py
      
      - name: Start local backend deployment
        run: |
          cd backend/
          python3 app.py

      - name: Run integration tests (local)
        run: |
          cd backend/tests/
          pytest *integrationTests.py

      - name: Remove local backend deployment
        run: pkill -f "python3 app.py"
        if: always()
